FROM n8nio/n8n:1.62.0

ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_DATABASE=${PGDATABASE}
ENV DB_POSTGRESDB_HOST=${PGHOST}
ENV DB_POSTGRESDB_PORT=${PGPORT}
ENV DB_POSTGRESDB_USER=${PGUSER}
ENV DB_POSTGRESDB_PASSWORD=${PGPASSWORD}
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=${USERNAME}
ENV N8N_BASIC_AUTH_PASSWORD=${PASSWORD}
ENV GENERIC_TIMEZONE=Europe/Prague

EXPOSE 5678

CMD ["n8n"]
