FROM n8nio/n8n:latest

# Nastavení proměnných prostředí (Railway si je předá z UI)
ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_DATABASE=${PGDATABASE}
ENV DB_POSTGRESDB_HOST=${PGHOST}
ENV DB_POSTGRESDB_PORT=${PGPORT}
ENV DB_POSTGRESDB_USER=${PGUSER}
ENV DB_POSTGRESDB_PASSWORD=${PGPASSWORD}

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=${USERNAME}
ENV N8N_BASIC_AUTH_PASSWORD=${PASSWORD}

# Otevřít port n8n UI
EXPOSE 5678

# Spustit n8n přes npx
CMD ["npx", "n8n"]
